/**
 * Plan & Benefits module: Plan Registry (CONTRACT §2) and DPPO benefit engine (§3).
 * Plan data is generated by data/tools/build-registry.ts and statically imported here.
 */
import {
  addDays,
  AUTHORITATIVE_SOURCE_ROLES,
  CONTRACT_VERSION,
  ENGINE_IDS,
  formatUsd,
  isWithin,
  issue,
  localDateOf,
  PlanDefinition,
  PlanRegistry,
  RuleStatus,
  ruleStructuralProblems,
  samePlanKey,
  ServiceClass,
  type BenefitPassport,
  type EvidenceIndexEntry,
  type Issue,
  type MemberState,
  type PassportItem,
  type PlanOptionsResult,
  type PlanOptionSummary,
  type PlanRule,
  type PlanValidationReport,
  type SourcedMoney,
} from "@/domain";
import type { BenefitEngine, BenefitsModule } from "@/domain/ports";
import enhanced2026 from "../../data/plans/nwd-ppo-enhanced-2026.json";
import enhanced2027 from "../../data/plans/nwd-ppo-enhanced-2027.json";
import plan2026 from "../../data/plans/nwd-ppo-standard-2026.json";
import plan2027 from "../../data/plans/nwd-ppo-standard-2027.json";
import value2026 from "../../data/plans/nwd-ppo-value-2026.json";
import value2027 from "../../data/plans/nwd-ppo-value-2027.json";
import sources from "../../data/plans/sources.generated.json";
import { cmp, normalizeIssues, resolvePlanVersion, rulesOf, supportsPlanType } from "./rules";
import { money, openLedger, openPeriod, simulate } from "./simulate";

const REGISTRY_VERSION = "synthetic-2026.10.04-six-plan";

let cached: PlanRegistry | null = null;

export function loadRegistry(): PlanRegistry {
  cached ??= PlanRegistry.parse({
    registry_version: REGISTRY_VERSION,
    plans: [plan2026, plan2027, value2026, value2027, enhanced2026, enhanced2027],
    sources,
  });
  return cached;
}

// ---------------------------------------------------------------------------
// §2.4 validatePlan
// ---------------------------------------------------------------------------

function validatePlan(registry: PlanRegistry, plan: PlanDefinition): PlanValidationReport {
  const issues: Issue[] = [];
  const parsed = PlanDefinition.safeParse(plan);
  if (!parsed.success) {
    for (const e of parsed.error.issues) {
      issues.push(issue("SCHEMA_INVALID", "blocking", "Plan definition does not match the schema.", { field: e.path.join(".") || null }));
    }
  } else {
    const seen = new Set<string>();
    for (const r of plan.rules) {
      if (seen.has(r.rule_id)) issues.push(issue("RULE_CONFLICT", "blocking", "Duplicate rule id.", { rule_id: r.rule_id }));
      seen.add(r.rule_id);
      for (const p of ruleStructuralProblems(r)) issues.push(issue("SCHEMA_INVALID", "blocking", p, { rule_id: r.rule_id }));
      let authoritative = false;
      for (const e of r.evidence) {
        const src = registry.sources.find((s) => s.source_id === e.source_id && s.plan_version_ids.includes(plan.plan_version_id));
        const page = src?.pages.find((p) => p.page === e.page);
        if (!page?.text.includes(e.quote)) {
          issues.push(issue("RULE_EVIDENCE_MISSING", "blocking", `Evidence quote not found on page ${e.page} of ${e.source_id}.`, { rule_id: r.rule_id }));
        }
        if (src && AUTHORITATIVE_SOURCE_ROLES.includes(src.document_role)) authoritative = true;
      }
      // (1.4) PLAN-003: educational material never backs a rule used in a calculation.
      if (r.status === "VERIFIED" && r.evidence.length > 0 && !authoritative) {
        issues.push(issue("SOURCE_NOT_AUTHORITATIVE", "blocking", `Rule ${r.rule_id} is backed only by non-authoritative sources.`, { rule_id: r.rule_id }));
      }
    }
    for (const d of plan.source_documents) {
      if (registry.sources.find((s) => s.source_id === d.source_id)?.sha256 !== d.sha256) {
        issues.push(issue("SOURCE_CHECKSUM_MISMATCH", "blocking", `Source ${d.source_id} checksum does not match the registry.`, { field: "source_documents" }));
      }
    }
    // (1.4) PLAN-003: source_precedence is a permutation of source_documents.
    const docIds = plan.source_documents.map((d) => d.source_id).sort();
    const precedence = [...plan.source_precedence].sort();
    if (precedence.length !== docIds.length || precedence.some((id, i) => id !== docIds[i])) {
      issues.push(issue("SOURCE_PRECEDENCE_INVALID", "blocking", "Source precedence must list each plan source exactly once.", { field: "source_precedence" }));
    }
  }
  const rule_counts = Object.fromEntries(RuleStatus.options.map((s) => [s, 0])) as Record<RuleStatus, number>;
  for (const r of Array.isArray(plan.rules) ? plan.rules : []) if (r.status in rule_counts) rule_counts[r.status] += 1;
  const sorted = normalizeIssues(issues);
  return { plan_version_id: plan.plan_version_id, ok: !sorted.some((i) => i.severity === "blocking"), rule_counts, issues: sorted };
}

// ---------------------------------------------------------------------------
// §3.7 Benefit Passport
// ---------------------------------------------------------------------------

type Value = Pick<PassportItem, "value_cents" | "value_range" | "value_bps" | "value_date" | "value_text">;
const NO_VALUE: Value = { value_cents: null, value_range: null, value_bps: null, value_date: null, value_text: null };

function inputItem(item_id: string, label: string, m: SourcedMoney, cents: number | null, extraInputs: string[] = []): PassportItem {
  return {
    item_id,
    label,
    ...NO_VALUE,
    ...(cents === null ? { value_text: "Unknown; please confirm" } : { value_cents: cents }),
    source: cents === null ? "NEEDS_CONFIRMATION" : m.source,
    rule_status: null,
    rule_ids: [],
    input_ids: [m.input_id, ...extraInputs],
    observed_at: m.observed_at,
  };
}

function ruleItem(item_id: string, label: string, r: PlanRule | undefined, verified: (r: PlanRule) => Partial<Value>): PassportItem[] {
  if (!r) return [];
  const usable = r.status === "VERIFIED" || r.status === "NOT_APPLICABLE";
  const text =
    r.status === "NOT_APPLICABLE" ? null : r.status === "UNKNOWN" ? "Not addressed in the plan document" : r.status === "VERIFIED" ? null : "Needs confirmation with the plan";
  const value: Value = { ...NO_VALUE, ...(r.status === "VERIFIED" || r.status === "NOT_APPLICABLE" ? verified(r) : { value_text: text }) };
  return [
    {
      item_id,
      label,
      ...value,
      source: usable ? "PLAN_VERIFIED" : "NEEDS_CONFIRMATION",
      rule_status: r.status,
      rule_ids: [r.rule_id],
      input_ids: [],
      observed_at: null,
    },
  ];
}

const CLASS_LABEL = { preventive: "Diagnostic & preventive", basic: "Basic", major: "Major", orthodontic: "Orthodontic" } as const;

const firstRule = <T extends PlanRule["rule_type"]>(plan: PlanDefinition, t: T) => rulesOf(plan, t)[0];

/** Coverage rate per service class for one network (passport and plan options). */
function coverageItems(plan: PlanDefinition, network: "in_network" | "out_of_network"): PassportItem[] {
  return ServiceClass.options.flatMap((cls) =>
    ruleItem(
      `coverage.${network}.${cls}`,
      CLASS_LABEL[cls],
      rulesOf(plan, "plan_share").find((r) => r.applies_when.network === network && r.applies_when.service_class === cls),
      (r) => (r.rule_type === "plan_share" && r.value ? { value_bps: r.value.rate_bps } : { value_text: "Not covered" }),
    ),
  );
}

/**
 * (1.6) One plan-wide waiting rule → the single `rules.waiting_period` item. Per-class rules →
 * one item per class, so a 12-month Major wait is never summarized as "No waiting periods".
 */
function waitingItems(plan: PlanDefinition): PassportItem[] {
  const waits = rulesOf(plan, "waiting_period");
  const months = (r: PlanRule, none: string) => ({ value_text: r.rule_type === "waiting_period" && r.value ? `${r.value.months} months` : none });
  if (waits.length === 1 && waits[0]!.applies_when.service_class === null) {
    return ruleItem("rules.waiting_period", "Waiting periods", waits[0], (r) => months(r, "No waiting periods"));
  }
  const order = (r: PlanRule) => (r.applies_when.service_class === null ? -1 : ServiceClass.options.indexOf(r.applies_when.service_class));
  return [...waits]
    .sort((a, b) => order(a) - order(b))
    .flatMap((w) => {
      const cls = w.applies_when.service_class;
      return ruleItem(`rules.waiting_period.${cls ?? "all"}`, `Waiting period: ${cls ? CLASS_LABEL[cls] : "all services"}`, w, (r) => months(r, "No waiting period"));
    });
}

/** Plan-rule items shared by the passport and plan options. */
function planRuleItems(plan: PlanDefinition): PassportItem[] {
  const nextReset = addDays(plan.coverage_period.end, 1);
  return [
    ...ruleItem("rules.benefit_period", "Balances reset on", firstRule(plan, "benefit_period"), () => ({ value_date: nextReset })),
    ...ruleItem("rules.deductible", "Deductible", firstRule(plan, "deductible"), (r) =>
      r.rule_type === "deductible" && r.value ? { value_cents: r.value.individual_cents } : {},
    ),
    ...ruleItem("rules.annual_maximum", "Annual maximum", firstRule(plan, "annual_maximum"), (r) =>
      r.rule_type === "annual_maximum" && r.value ? { value_cents: r.value.individual_cents } : {},
    ),
    ...waitingItems(plan),
    ...ruleItem("rules.rollover", "Unused maximum carryover", firstRule(plan, "rollover"), (r) => ({
      value_text:
        r.rule_type === "rollover" && r.value
          ? `Up to ${formatUsd(r.value.base_award_cents)}${r.value.network_bonus_cents > 0 ? ` (+${formatUsd(r.value.network_bonus_cents)} in-network bonus)` : ""} next year if plan payments stay ${r.value.threshold_comparison === "LT" ? "below" : "at or below"} ${formatUsd(r.value.threshold_cents)}; balance capped at ${formatUsd(r.value.bank_cap_cents)}`
          : "No carryover",
    })),
    ...ruleItem("rules.claim_submission", "Paying a network dentist directly", firstRule(plan, "claim_submission"), (r) => ({
      value_text:
        r.rule_type === "claim_submission" && r.value?.member_may_decline_claim
          ? "Allowed; paid services do not use your plan balances"
          : "Claims are always submitted",
    })),
  ];
}

function passport(registry: PlanRegistry, member: MemberState, asOf: string): BenefitPassport {
  const asOfDate = localDateOf(asOf, member.time_zone);
  const res = resolvePlanVersion(registry, member.plan_key, asOfDate);
  if (!res.ok) throw new Error(`passport: ${res.issues[0]!.code}`);
  const plan = res.plan;
  const snap = member.accumulators.find((a) => a.plan_version_id === plan.plan_version_id);
  if (!snap) throw new Error("passport: INPUT_MISSING member.accumulators");
  const period = openPeriod(registry, plan, member, asOfDate, "worst_case");
  if (!period.state) throw new Error("passport: INPUT_MISSING member.accumulators");
  const st = period.state;
  const pending = member.pending_claims.filter((c) => c.plan_version_id === plan.plan_version_id);
  const pendingMax = pending.map((c) => c.estimated_plan_pay.input_id);
  const pendingDed = pending.map((c) => c.estimated_deductible_applied.input_id);

  const balances: PassportItem[] = [
    inputItem("balances.deductible_remaining", "Deductible remaining", snap.deductible_remaining, st.deductible_remaining_cents),
    inputItem("balances.deductible_available", "Deductible still to meet (after pending claims)", snap.deductible_remaining, st.deductible_available_cents, pendingDed),
    inputItem("balances.annual_max_remaining", "Annual maximum remaining", snap.annual_max_remaining, st.annual_max_remaining_cents),
    ...(pending.length
      ? [inputItem("balances.pending_reserved_max", "Reserved for pending claims", pending[0]!.estimated_plan_pay, st.pending_reserved_max_cents, pendingMax.slice(1))]
      : []),
    inputItem("balances.annual_max_available", "Annual maximum available now", snap.annual_max_remaining, st.annual_max_available_cents, pendingMax),
    inputItem("balances.plan_paid_ytd", "Plan paid this year", snap.plan_paid_ytd, money(snap.plan_paid_ytd, "worst_case", "higher_is_better")),
  ];

  const nextReset = addDays(plan.coverage_period.end, 1);
  const funding: PassportItem[] = [
    ...[...member.funding_accounts]
      .sort((a, b) => (a.source_id < b.source_id ? -1 : 1))
      .flatMap((a) => [
        inputItem(`funding.${a.source_id}.balance`, `${a.type} balance`, a.balance, money(a.balance, "worst_case", "higher_is_better")),
        ...(a.eligible_service_through
          ? [
              {
                item_id: `funding.${a.source_id}.service_through`,
                label: `${a.type} covers services through`,
                ...NO_VALUE,
                value_date: a.eligible_service_through,
                source: a.balance.source,
                rule_status: null,
                rule_ids: [],
                input_ids: [a.balance.input_id],
                observed_at: a.balance.observed_at,
              },
            ]
          : []),
      ]),
    {
      item_id: "funding.monthly_budget",
      label: "Monthly budget (hard limit)",
      ...NO_VALUE,
      value_cents: member.budget.hard_monthly_limit_cents,
      source: member.budget.source,
      rule_status: null,
      rule_ids: [],
      input_ids: [member.budget.input_id],
      observed_at: member.budget.observed_at,
    },
  ];

  return {
    contract_version: CONTRACT_VERSION,
    as_of: asOf,
    member_id: member.member_id,
    plan_version_id: plan.plan_version_id,
    plan_name: plan.plan_name,
    carrier_name: plan.carrier_name,
    synthetic: plan.synthetic,
    coverage_period_start: plan.coverage_period.start,
    coverage_period_end: plan.coverage_period.end,
    next_reset_date: nextReset,
    current_period: st,
    sections: [
      { section_id: "balances", title: "Your balances", items: balances },
      { section_id: "coverage_in_network", title: "In-network coverage", items: coverageItems(plan, "in_network") },
      { section_id: "coverage_out_of_network", title: "Out-of-network coverage", items: coverageItems(plan, "out_of_network") },
      { section_id: "rules", title: "Plan rules", items: planRuleItems(plan) },
      { section_id: "funding", title: "Funding", items: funding },
    ],
    issues: normalizeIssues(period.issues),
  };
}

// ---------------------------------------------------------------------------
// (1.6) §3.10 Plan options
// ---------------------------------------------------------------------------

const PREMIUM_TIER_LABEL = {
  EMPLOYEE_ONLY: "employee only",
  EMPLOYEE_SPOUSE: "employee + spouse",
  EMPLOYEE_CHILDREN: "employee + child(ren)",
  FAMILY: "family",
} as const;

/** One item per documented tier; a non-verified premium is one needs-confirmation item, never $0. */
function premiumItems(plan: PlanDefinition): PassportItem[] {
  const r = firstRule(plan, "premium");
  if (r?.status !== "VERIFIED" || !r.value) return ruleItem("premium", "Monthly premium", r, () => ({}));
  return r.value.tiers.flatMap((t) =>
    ruleItem(`premium.${t.coverage_tier.toLowerCase()}`, `Monthly premium: ${PREMIUM_TIER_LABEL[t.coverage_tier]}`, r, () => ({ value_cents: t.cents })),
  );
}

function orthodonticItems(plan: PlanDefinition): PassportItem[] {
  return ruleItem("rules.orthodontic_lifetime_maximum", "Orthodontic lifetime maximum", firstRule(plan, "lifetime_maximum"), (r) =>
    r.rule_type === "lifetime_maximum" && r.value ? { value_cents: r.value.individual_cents } : { value_text: "Orthodontics not covered" },
  );
}

function planOptions(registry: PlanRegistry, member: MemberState, asOf: string): PlanOptionsResult {
  const asOfDate = localDateOf(asOf, member.time_zone);
  const k = member.plan_key;
  const own = resolvePlanVersion(registry, k, asOfDate);
  const options: PlanOptionSummary[] = registry.plans
    .filter(
      (p) =>
        p.key.carrier_id === k.carrier_id &&
        p.key.group_id === k.group_id &&
        p.key.jurisdiction === k.jurisdiction &&
        isWithin(asOfDate, p.coverage_period.start, p.coverage_period.end),
    )
    .sort((a, b) => cmp(a.key.plan_option_id, b.key.plan_option_id) || cmp(a.plan_version_id, b.plan_version_id))
    .map((p) => ({
      plan_version_id: p.plan_version_id,
      plan_id: p.plan_id,
      plan_option_id: p.key.plan_option_id,
      plan_name: p.plan_name,
      plan_type: p.plan_type,
      coverage_period_start: p.coverage_period.start,
      coverage_period_end: p.coverage_period.end,
      is_member_plan: samePlanKey(p.key, k),
      adjudication_supported: supportsPlanType(p.plan_type),
      items: [...premiumItems(p), ...coverageItems(p, "in_network"), ...coverageItems(p, "out_of_network"), ...planRuleItems(p), ...orthodonticItems(p)],
    }));
  return {
    contract_version: CONTRACT_VERSION,
    as_of: asOf,
    member_plan_version_id: own.ok ? own.plan.plan_version_id : null,
    options,
    issues: own.ok
      ? []
      : [issue("PLAN_NOT_FOUND", "info", `Your own plan has no version effective on ${asOfDate}; other options are still listed.`, { field: "member.plan_key" })],
  };
}

function evidenceFor(registry: PlanRegistry, ruleIds: readonly string[], planVersionIds?: readonly string[]): EvidenceIndexEntry[] {
  const wanted = new Set(ruleIds);
  const versions = planVersionIds ? new Set(planVersionIds) : null;
  return registry.plans
    .filter((plan) => !versions || versions.has(plan.plan_version_id))
    .flatMap((p) =>
      p.rules
        .filter((r) => wanted.has(r.rule_id) && r.evidence.length > 0)
        .map((r) => ({ rule_id: r.rule_id, plan_version_id: p.plan_version_id, evidence: r.evidence })),
    )
    .sort((a, b) => cmp(a.rule_id, b.rule_id) || cmp(a.plan_version_id, b.plan_version_id));
}

export const benefitEngine: BenefitEngine = {
  engine_id: ENGINE_IDS.benefits,
  supportsPlanType,
  validatePlan,
  resolvePlanVersion,
  openLedger,
  simulate,
  passport,
  planOptions,
  evidenceFor,
};

export const benefitsModule = { benefitEngine, loadRegistry } satisfies BenefitsModule;
