"use client";

import type { MemberBenefitContext } from "@analysis/types";
import { formatCents } from "@/lib/domain/money";

export function MemberBenefitContextPanel({ context }: { context: MemberBenefitContext }) {
  const values: [string, number | null][] = [["Annual maximum (base plan)", context.annualMaximumCents], ["Plan paid year to date (settled)", context.settledPlanPaidCents], ["Base remaining before pending", context.baseRemainingCents], ["Pending projected plan payment reservation", context.pendingProjectedPlanPaymentCents], ["Base available after pending reservation", context.baseAvailableAfterPendingCents], ["Deductible remaining", context.deductibleRemainingCents], ["Rollover bank (separate)", context.rolloverBankCents]];
  return <section aria-label="Server-checked member benefits" className="space-y-3 rounded-xl border bg-card p-4 text-sm"><h2 className="font-semibold">Synthetic member benefits · {context.memberId} · {context.planName}</h2>{context.status === "CONSERVATIVE" && <div className="rounded-lg border border-primary/25 bg-accent p-3"><p className="font-semibold text-primary">Conservative base-benefit estimate</p><p className="mt-1">Pending projected plan payments are reserved separately from settled payments. Pending deductible effects remain unchanged. The unconfirmed rollover bank is excluded from available benefits. This is a partial estimate, not a complete claim-settlement result.</p></div>}<p className="text-muted-foreground">Benefit year {context.benefitYear} · Source {context.sourceStatus} · Observed {context.observedAt} · Plan {context.planVersionId}</p><dl className="grid gap-3 sm:grid-cols-2">{values.map(([label, value]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd>{value === null ? "Needs confirmation" : formatCents(value)}</dd></div>)}</dl>{context.status === "NEEDS_CONFIRMATION" && <p className="font-medium text-destructive">A complete cost estimate needs confirmation of these benefit facts.</p>}<ul className="list-disc space-y-1 pl-5">{context.issues.map((issue) => <li key={issue}>{issue}</li>)}</ul></section>;
}
